wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_001.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_004.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_005.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_007.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_009.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_010.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_011.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_011ya.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_012.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_013.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_013sp.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_014.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_015.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_016.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_017.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_018.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_019.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_020.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_022.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_022id.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_024.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_025.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_026.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_027.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_028.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_028bk.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_028sp.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_029.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_030.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_050.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_051ki.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_051on.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_051sp.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_056.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_058.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_065.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_082.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_090.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_092.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_099.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_1000.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_999.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_k10.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_n07.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_n08.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_n09.gif
wget http://cache001.ranking.goo.ne.jp/ranking/img/g_icon/i_s001.gif
